// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	vo "github.com/bosamatheus/better-shipping/shipping-recommendations/internal/vo"
)

// UseCase is an autogenerated mock type for the UseCase type
type UseCase struct {
	mock.Mock
}

// GetShippingRecommendations provides a mock function with given fields:
func (_m *UseCase) GetShippingRecommendations() ([]vo.ShippingOption, error) {
	ret := _m.Called()

	var r0 []vo.ShippingOption
	if rf, ok := ret.Get(0).(func() []vo.ShippingOption); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]vo.ShippingOption)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
