// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Logger is an autogenerated mock type for the Logger type
type Logger struct {
	mock.Mock
}

// InfoMsg provides a mock function with given fields: msg
func (_m *Logger) InfoMsg(msg string) {
	_m.Called(msg)
}

// InvalidArgErr provides a mock function with given fields: argName
func (_m *Logger) InvalidArgErr(argName string) {
	_m.Called(argName)
}

// InvalidArgValErr provides a mock function with given fields: argName, argVal
func (_m *Logger) InvalidArgValErr(argName string, argVal string) {
	_m.Called(argName, argVal)
}

// MissingArgErr provides a mock function with given fields: argName
func (_m *Logger) MissingArgErr(argName string) {
	_m.Called(argName)
}

// UnexpectedErr provides a mock function with given fields: err
func (_m *Logger) UnexpectedErr(err error) {
	_m.Called(err)
}
