// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Logger is an autogenerated mock type for the Logger type
type Logger struct {
	mock.Mock
}

// DefaultError provides a mock function with given fields: err
func (_m *Logger) DefaultError(err error) {
	_m.Called(err)
}

// InvalidArgError provides a mock function with given fields: argumentName
func (_m *Logger) InvalidArgError(argumentName string) {
	_m.Called(argumentName)
}

// InvalidArgValueError provides a mock function with given fields: argumentName, argumentValue
func (_m *Logger) InvalidArgValueError(argumentName string, argumentValue string) {
	_m.Called(argumentName, argumentValue)
}

// MissingArgError provides a mock function with given fields: argumentName
func (_m *Logger) MissingArgError(argumentName string) {
	_m.Called(argumentName)
}
