name: shipping-recommendations
on:
  push:
    branches:
      - main
  pull_request:
defaults:
  run:
    working-directory: shipping-recommendations
permissions:
  contents: read
jobs:
  test:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
      - uses: actions/checkout@v2
      - name: Test coverage
        run: make test-cover
